### ISSUE TITLE
Publish passphrasemeter to Maven Central?

### ISSUE THREAD

**Issue by CamiloCon** [wultra/wultra-docs#16]
Since jcenter will be maintained as a read-only repository indefinitely. Are there any plans to move `passphrasemeter` away from it? Is it published only in jcenter? Maven central sounds like a good alternative.

**Comment by petrdvorak** [comment]
Hello @CamiloCon, thank you for the report - this seems to be more a discussion than an issue. Generally speaking, we do publish all new library versions to Maven Central. We keep existing releases in JCenter, which will remain read-only indefinitely. So the library updates will move to JCenter.
