### ISSUE TITLE
Server Side Tutorial

### ISSUE THREAD

**Issue by aerciyas** [wultra/wultra-docs#29]
In the Deploy the Server-Side Components section both the PowerAuth Server/Admin are returning 404's. 

A seen below, both applications are running in the tomcat manager, but will return 404 when visited. 
<img width="1238" alt="localhost-ServersideSetupTutorial" src="https://user-images.githubusercontent.com/6564954/210957526-cabe630b-521f-4118-afd6-923a0cab7d9f.png">

To reproduce, add either xml configuration file to $CATALINA_HOME/conf/Catalina/localhost/, and respective war files to $CATALINA_HOME/webapps, run tomcat. 

System using 
apache-tomcat-10.0.27
java 19.0.1

**Comment by romanstrobl** [comment]
Tomcat 10.x is not supported by Spring Boot 2.x. Please use Tomcat 9.x.

**Comment by petrdvorak** [comment]
Hello @ozzi88, please reach out to me directly via petr@wultra.com, and we will help you set everything up. 👍
